nelmio_api_doc:
    documentation:
        info:
            title: GOG test
            description: GOG Test app
            version: 1.0.0
        tags:
            - name: Products
              description: 'Products API'
            - name: Cart
              description: 'Cart API'
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/v1/api(?!/doc$) # Accepts routes under /api except /api/doc
